server.servlet-path: "/*"
server.contextPath: "/heartkidaustralia"
server.port: 8080

spring:
 profiles.active: test
---
spring:
  profiles: test
  datasource:
    url: "jdbc:h2:mem:heartkidsdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=MYSQL"
  jpa:
    database-platform: "org.hibernate.dialect.MySQLDialect"
    hibernate.ddl-auto: create
    hibernate.hbm2ddl.auto: create
    show-sql: true
  endpoints:
    enabled: true
    health.enabled: true
---
spring:
  profiles: production
  datasource:
    url: "jdbc:mysql://localhost:3306/heartkids"
    username: heartkidsdev
    password: tcscsr#1234
    driverClassName: "com.mysql.jdbc.Driver"
  jpa:
    database-platform: "org.hibernate.dialect.MySQLDialect"
    hibernate.ddl-auto: update
    hibernate.hbm2ddl.auto: create
    show-sql: true
  endpoints:
    enabled: false
    health.enabled: true
---

mailfromId: nirmal5031@gmail.com
mail.smtp.host: localhost
mail.smtp.port: 25
